[trinusvr]
pid = '17084'
address = "0x0261AC78"

[cases]
channel_width = [20, 40]
image_quality = ["ultra"]
compress_level = [0]
bulk_flow = [3]
priority_dscp = ["AC_BE"]
loop = 5
time = 30
replace_vr_by_iperf = true